Transform: AWS::Serverless-2016-10-31
Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /products:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetProducts.Arn}/invocations
              responses: {}
            post:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CreateProduct.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
      Cors:
        MaxAge: 5
  GetProducts:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetProducts
      CodeUri: src/getProducts
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Events:
        ApiGETproducts:
          Type: Api
          Properties:
            Path: /products
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref Products
          PRODUCTS_TABLE_ARN: !GetAtt Products.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Products
  GetProductsLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetProducts}
  Products:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  CreateProduct:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: CreateProduct
      CodeUri: src/createProduct
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 1024
      Timeout: 30
      Tracing: Active
      Events:
        ApiPOSTproducts:
          Type: Api
          Properties:
            Path: /products
            Method: POST
            RestApiId: !Ref Api
      Environment:
        Variables:
          PRODUCTS_TABLE_NAME: !Ref Products
          PRODUCTS_TABLE_ARN: !GetAtt Products.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Products
  CreateProductLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${CreateProduct}